server:
  port: 9001


spring:
  application:
    #服务名
    name: openfeign9001


  cloud:
    #注册中心
    nacos:
      discovery:
        ###服务注册地址
        server-addr: 127.0.0.1:8848
        #server-addr: 127.0.0.1:8848
    #熔断限流
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
      #sentinel 持久化到 nacos
      datasource:
        ds1:    #数据源1
          nacos:
            server-addr=localhost: 8848  #nacos 地址
            data-id: ${spring.application.name}  #配置文件id（一般使用本服务名）
            group-id: DEFAULT_GROUP      #默认 分组
            data-type: json              #数据类型 json
            rule-type: flow


  #数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springcloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:   #连接超时的问题
      idle-timeout: 60000
      connection-timeout: 60000
      login-timeout: 3000
      max-lifetime: 60000

#mybatis:
#  mapper-locations: classpath:mappers/*.xml
#  config-location: classpath:mybatis-config.xml


#mybatisplus配置
mybatis-plus:
  mapper-locations: classpath:**/mapper/xml/*.xml #指定mapper.xml路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #开启日志打印

#激活 sentinel 对 feign 的支持，要不然 @FeignClient中的 fallback 不起作用
feign:
  sentinel:
    enabled: true


