server:
  port: 9527


spring:
  application:
    #服务名
    name: cloud-gateway

  cloud:
    #注册中心
    nacos:
      discovery:
        ###服务注册地址
        server-addr: liguanghao.top:8848
    #网关
    gateway:
      discovery:
        locator:
            enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由

      routes:
        - id: cloud-payment-service #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #通过注册中心找到的8001的服务名
          predicates:
            - Path=/payment/hystrix/** #断言,路径相匹配的进行路由
